### ISSUE TITLE
Does not build on development SBCL - defconstant of CL:ERROR

### ISSUE THREAD

**Issue by quicklisp** [taksatou/cl-gearman#1]
The defconstant of cl:error in protocol.lisp signals an error in the latest git version of SBCL due to package locks.

A full log is here: http://report.quicklisp.org/2015-07-28/failure-report/cl-gearman.html#cl-gearman

**Comment by quicklisp** [comment]
Any word on this?

**Comment by taksatou** [comment]
In my environment, it seems ok now. Does this fix the problem?

**Comment by quicklisp** [comment]
It builds properly now, thank you!

**Comment by taksatou** [comment]
Thanks!
